name: esy CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches: [main]

jobs:
  cabal:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'

    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Install esy
      run: |
        npm install -g esy

    - uses: actions/cache@v2.1.3
      name: Cache ~/.esy
      with:
        path: ~/.esy
        key: ${{ runner.os }}-${{ hashFiles('esy.lock/index.json') }}

    - name: Install dependencies
      run: |
        esy install

    - name: Build
      run: |
        esy

    - name: Test
      if: matrix.os != 'windows-latest'
      run: |
        esy test
